vim.keymap.set("n","<space><space>x","<cmd>source %<CR>")
vim.keymap.set("n","<space><space>s","<cmd>w<CR>")
vim.keymap.set("n","<space><space>e","<cmd>Lexplore 30<CR>")
vim.keymap.set("n","<space>er","<cmd>Explore 30<CR>")
vim.keymap.set("n","-","<cmd>lua MiniFiles.open()<CR>")
